// ENDPOINTS NOTES //

// GET all documents/notes
# @name getNotes
GET http://localhost:3000/notes

###

// GET specific document 
GET http://localhost:3000/notes/1

###

POST http://localhost:3000/notes/add
Content-Type: application/json

{
  "title": "Test Note",
  "content": "This is a test note."
}

###

PUT http://localhost:3000/notes/1/update
Content-Type: application/json

{
  "title": "Updated Title",
  "content": "Updated Content"
}


###

DELETE http://localhost:3000/notes/1

###


# @name users
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "fanny@mail.com",
    "password": "fanny"
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "test"
}

###